name: Deploy Vite Apps to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # CLIENT
      - name: Install client dependencies
        run: npm install
        working-directory: client

      - name: Build client
        run: npm run build
        working-directory: client

      # ADMIN
      - name: Install admin dependencies
        run: npm install
        working-directory: admin

      - name: Build admin
        run: npm run build
        working-directory: admin

      # Upload client
      - name: Upload client
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: client/dist/
          server-dir: public_html/

      # Upload admin
      - name: Upload admin
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: admin/dist/
          server-dir: public_html/admin/
